name: Update package-lock.json

on:
  schedule:
    - cron: "0 8 * * 5"
  push:
    branches:
      - main

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Update node deps
        run: |
          REPO_LIST=()
          REPO_LIST+=(arpes-manual)
          REPO_LIST+=(arpespythontools)
          REPO_LIST+=(condmat-notes)
          REPO_LIST+=(espresso)
          REPO_LIST+=(fortran)
          REPO_LIST+=(javascript)
          REPO_LIST+=(linux)
          REPO_LIST+=(machine-learning)
          REPO_LIST+=(openmx)
          REPO_LIST+=(python-tutorial)
          REPO_LIST+=(rust)
          REPO_LIST+=(suvtools)
          
          for REPO_NAME in "${REPO_LIST[@]}"
          do git clone --depth 1 https://github.com/pranabdas/${REPO_NAME}
            cd ${REPO_NAME}
            npx --yes npm-check-updates --target minor --upgrade
            rm package-lock.json
            npm install
            npm install --save-exact @docusaurus/core@canary @docusaurus/preset-classic@canary
            npm run build
            cp package.json ../${REPO_NAME}-package.json
            cp package-lock.json ../${REPO_NAME}-package-lock.json
            cd ..
            rm -rf ${REPO_NAME}
          done
          
          git clone --depth 1 https://github.com/pranabdas/c-cpp
          cd c-cpp
          npx --yes npm-check-updates --target minor --upgrade
          rm package-lock.json
          npm install
          npm install --save-exact @docusaurus/core@canary @docusaurus/preset-classic@canary @docusaurus/theme-mermaid@canary
          npm run build
          cp package.json ../c-cpp-package.json
          cp package-lock.json ../c-cpp-package-lock.json
          cd ..
          rm -rf c-cpp

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update package-lock.json
          branch: updates
          delete-branch: true
          title: 'Update dependencies'
          body: |
            Auto-generated pull request to update package-lock.json
          labels: |
            automated pr
          draft: false
