name: Update package-lock.json

on:
  schedule:
    - cron: "0 8 * * 5"
  push:
    branches:
      - main
# env:
#   REPO_NAME: arpespythontools

jobs:
  create-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Clone repo
        run: |
          git clone --depth 1 https://github.com/pranabdas/arpespythontools
      - name: Update package-lock
        working-directory: arpespythontools
        run: |
          npx npm-check-updates --target minor --upgrade
          rm package-lock.json
          npm install

      - name: Copy package-lock.json
        run: |
          cp arpespythontools/package-lock.json ./arpespythontools-package-lock.json
          cp arpespythontools/package.json ./arpespythontools-package.json
          rm -rf arpespythontools

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update package-lock.json
          branch: update-package-lock
          delete-branch: true
          title: 'Update package-lock.json(arpespythontools)'
          body: |
            Auto-generated pull request to update package-lock.json
          labels: |
            automated pr
          draft: false
